language: python

python:
  - 3.6

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - poetry install

script:
  - poetry run py.test --cov=scarecrow tests